# AgentBlueprint - Multi-Agent Workflow Example

agents:
  researcher:
    model: openai:gpt-4
    system_prompt: |
      You are a thorough researcher. When given a topic:
      1. Search for relevant information
      2. Verify facts from multiple sources
      3. Organize findings clearly
      
      Provide comprehensive notes for the writer.
    
    tools:
      - web_search
      - python_repl
    
    max_iterations: 3

  writer:
    model: openai:gpt-4
    system_prompt: |
      You are a skilled technical writer. 
      Given research notes, create clear, engaging content that:
      - Explains concepts simply
      - Uses examples
      - Maintains technical accuracy
    
    tools: []
    temperature: 0.7

workflow:
  type: sequential
  
  steps:
    - id: research
      agent: researcher
      input: "{{ user_input }}"
      output_var: research_notes
    
    - id: write
      agent: writer
      input: |
        Create a clear explanation based on these research notes:
        
        {{ research_notes }}
      output_var: final_content

  output: "{{ final_content }}"

config:
  max_total_iterations: 10
  timeout_seconds: 300
  log_level: INFO
